/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMS1;

import java.awt.Color;

/**
 *
 * @author 562915
 */
public class WelcomePanel extends javax.swing.JPanel {

    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        ProceedButton = new javax.swing.JLabel();
        TitleTextArea = new javax.swing.JTextArea();

        Panel.setBackground(new java.awt.Color(247, 247, 247));

        ProceedButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ProceedButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProceedButton.setText("Proceed");
        ProceedButton.setToolTipText("");
        ProceedButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ProceedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProceedButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProceedButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProceedButtonMousePressed(evt);
            }
        });

        TitleTextArea.setBackground(new java.awt.Color(247, 247, 247));
        TitleTextArea.setColumns(20);
        TitleTextArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        TitleTextArea.setRows(5);
        TitleTextArea.setText("Welcome to the \nEmployee Management System\n(EMS)!");
        TitleTextArea.setAutoscrolls(false);
        TitleTextArea.setBorder(null);
        TitleTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TitleTextArea.setFocusable(false);
        TitleTextArea.setRequestFocusEnabled(false);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(TitleTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(TitleTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(ProceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProceedButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProceedButtonMouseEntered
        ProceedButton.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_ProceedButtonMouseEntered

    private void ProceedButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProceedButtonMouseExited
        // TODO add your handling code here:
        ProceedButton.setBackground(new Color(247, 247, 247));
    }//GEN-LAST:event_ProceedButtonMouseExited

    private void ProceedButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProceedButtonMousePressed

    }//GEN-LAST:event_ProceedButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel ProceedButton;
    private javax.swing.JTextArea TitleTextArea;
    // End of variables declaration//GEN-END:variables
}
